---
# tasks file for git
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install git
  ansible.builtin.package:
    name: git

- name: Set git system name
  community.general.git_config:
    name: user.name
    scope: system
    value: "{{ git_name }}"

- name: Set git system email
  community.general.git_config:
    name: user.email
    scope: system
    value: "{{ git_email }}"

- name: Set git system default branch
  community.general.git_config:
    name: init.defaultBranch
    scope: system
    value: "{{ git_branch }}"

- name: Set git system default branch
  community.general.git_config:
    name: core.editor
    scope: system
    value: "{{ git_editor }}"
